### DISCUSSION TITLE
Best approach to use it with Home Assistant and an existing lock?

### DISCUSSION THREAD

**Discussion by eigenphase** [rednblkx/HomeKey-ESP32#82] [Q&A]
Right now I have an existing lock and I want to use this project to add HomeKey capability using Home Assistant.

What is the best way to integrate it?

Problem I am currently facing is that it's not an actual lock and tapping should just unlock my real lock. But the state is aways 0 (unlocked) after the first tap because (clearly) it doesn't reset to locked. Hence I can't easily use the state as a trigger in Home Assistant.

**Comment by eigenphase** [comment]
I can unlock my house via my Apple watch now! Insane!! Never thought this would work. Thank you some much @rednblkx for this amazing work!

It even works through my stucco wall + sheathing with the 3$ version from Aliexpress. No need for me to bring a device out, I just taped it behind the exterior wall.

As to my question above, this is what I came up with so far:

```
alias: Security / Entrance / Homekey / Unlock
description: ""
trigger:
  - platform: device
    device_id: e05beb1f8184b691fc7399eb0effd7d7
    domain: lock
    entity_id: ff793240b34b5a413020b65108b51d9c
    type: unlocked
condition: []
action:
  - device_id: f04f85c1d868579f3849bb335ecd58c4
    domain: lock
    entity_id: 3b8f47e36f13d5f3c4ad2c127a414b40
    type: unlock
  - device_id: e05beb1f8184b691fc7399eb0effd7d7
    domain: lock
    entity_id: ff793240b34b5a413020b65108b51d9c
    type: lock
mode: single
```

Device `e05beb1f8184b691fc7399eb0effd7d7` is the HomeKey device. Device `f04f85c1d868579f3849bb335ecd58c4` is my actual door lock. So when HomeKey unlocks, then I unlock my actual lock plus I lock the HomeKey lock again for the next scan. 

I'm not sure how hacky this is though. Is this the best thing to do or is there a better approach?
